language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

sudo: false

# Also run the generated tests for particular libraries
matrix:
  include:
    - env: ARITH=octave-interval
      sudo: required
    - env: ARITH=IntervalArithmetic.jl TEST=Test
      sudo: required
      dist: trusty

before_install:
  -
    if [ "$ARITH" == "octave-interval" ]; then
      sudo add-apt-repository --yes ppa:octave/stable;
      sudo apt-get update -qq;
      sudo apt-get install -qq -y octave liboctave-dev libmpfr-dev;
    fi

  -
    if [ "$ARITH" == "IntervalArithmetic.jl" ]; then
      sudo add-apt-repository --yes ppa:staticfloat/julianightlies;
      sudo add-apt-repository --yes ppa:staticfloat/julia-deps;
      sudo apt-get update -qq;
      sudo apt-get install -qq julia;
    fi

install:
  - pip install .

  -
    if [ "$ARITH" == "octave-interval" ]; then
      octave --no-gui --eval "pkg install -forge interval";
    fi

  -
    if [ "$ARITH" == "IntervalArithmetic.jl" ]; then
      julia -q --eval 'Pkg.add("IntervalArithmetic")';
    fi

script:
  -
    if [ "$ARITH" == "" ]; then
      python -m itf1788 -s itl -o output;
    fi

  -
    if [ "$ARITH" == "octave-interval" ]; then
      python -m itf1788 -s itl -o output -c "(octave, native, interval)";
      find output -name "*.tst" -exec octave --no-gui "{}" ";";
    fi

  -
    if [ "$ARITH" == "IntervalArithmetic.jl" ]; then
      python -m itf1788 -s itl -o output -c "(julia, $TEST, IntervalArithmetic)";
      find output -name "*.jl" -exec julia "{}" ";";
    fi
